### ISSUE TITLE
what's inside config.php?

### ISSUE THREAD

**Issue by ShadowGameszz** [28andrew/controlMyVPS#1]
I've tried using "npm run build" but it didn't work and the project doesn't work without config.php

**Comment by 28andrew** [comment]
Look at config.defaults.php as a reference to create config.php

**Comment by Aniket999969** [comment]
can i get database

**Comment by 28andrew** [comment]
You'd have to have a MySQL database to use this application. Let me know if you need help setting one up on your server.
